GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/api/blogs/609aa0cb2ecc574a483b48b3

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikp1bGlhbiIsImlkIjoiNjA5ZDM4YjkyYTliNmY1MjYwOWUxZTcwIiwiaWF0IjoxNjIwOTIwMzM2fQ.0Bx-C_FvTnH2KqjIazME67HffAjUTjHZRKx0VmoFrNg

{
    "title": "Token",
    "author": "Hopefully works",
    "url": "https",
    "likes": "34256346"
} 

###
DELETE http://localhost:3003/api/blogs/60a276d85efc8f04984d7fdb

###
PUT http://localhost:3003/api/blogs/609fc8694eb12e363c0caa6f
Content-Type: application/json

{
    "likes": "888"
} 

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Julian",
    "name": "Julian",
    "password": "Julian"
} 
