GET http://localhost:3001/api/blogs

###

GET http://localhost:3001/api/blogs/609aa0cb2ecc574a483b48b3

###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikp1bGlhbiIsImlkIjoiNjA5ZDM4YjkyYTliNmY1MjYwOWUxZTcwIiwiaWF0IjoxNjIwOTIwMzM2fQ.0Bx-C_FvTnH2KqjIazME67HffAjUTjHZRKx0VmoFrNg

{
    "title": "Token",
    "author": "Hopefully works",
    "url": "https",
    "likes": "34256346"
} 

###
DELETE http://localhost:3001/api/blogs/609aa874b1ae4a5d701f04ed

###
PUT http://localhost:3001/api/blogs/609a878a9674135d24e4c2ec
Content-Type: application/json

{
    "likes": "888"
} 

